default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

local: &local
  host: localhost
  port: 5433
  username: 'postgres'

development:
  <<: *default
  <<: *local
  database: stubhub_development

test:
  <<: *default
  <<: *local
  database: stubhub_test

production:
  <<: *default
  database: stubhub_production
